import os
import json
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import uvicorn

app = FastAPI(title="Repo-Archi-Graph API", version="1.0.0")

# Configure CORS to allow frontend requests from any local origin
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/api/analyze")
async def get_architecture():
    """
    🤖 IBM Bob AI-Powered Architecture Analysis Endpoint
    
    This endpoint serves the architectural intelligence data generated by IBM Bob's
    advanced contextual reasoning capabilities. IBM Bob acts as a Virtual CTO to:
    
    1. DEPENDENCY MAPPING: Analyzes import statements, function calls, and module
       relationships across the entire codebase to construct a semantic dependency graph.
    
    2. BLAST RADIUS SCORING: Evaluates each file's impact on system stability by
       reasoning about coupling, fan-in/fan-out metrics, and cascading failure risks.
       Scores range from 1 (isolated, safe to modify) to 10 (critical, high-risk changes).
    
    3. ARCHITECTURAL DEBT AUDIT: Performs deep code analysis to identify SOLID principle
       violations, security vulnerabilities, performance bottlenecks, and maintainability
       issues. Provides brutally honest, actionable critiques for each component.
    
    4. SEMANTIC RELATIONSHIP EXTRACTION: Goes beyond simple imports to understand the
       architectural role of each file (orchestrator, data layer, utility, etc.) and
       generates human-readable relationship descriptions.
    
    The data returned by this endpoint is the result of IBM Bob's comprehensive analysis
    of the repository structure, code patterns, and architectural decisions. This enables
    developers to make informed decisions about refactoring, risk mitigation, and
    technical debt prioritization.
    
    Returns:
        JSON object containing:
        - nodes: List of files with AI-generated summaries, blast radius scores, LOC, and debt analysis
        - edges: Semantic relationships between files with intelligent labels
    """
    file_path = os.path.join("output", "architecture.json")
    
    # Check if the IBM Bob-generated architecture data file exists
    if not os.path.exists(file_path):
        raise HTTPException(
            status_code=404,
            detail="Architecture data not found. Please ensure IBM Bob has generated output/architecture.json."
        )
    
    try:
        # Read and parse the JSON file containing IBM Bob's architectural analysis
        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        
        # Return the AI-powered architectural intelligence to the frontend
        return data
    except json.JSONDecodeError as e:
        raise HTTPException(
            status_code=500,
            detail=f"Invalid JSON format in architecture.json: {str(e)}"
        )
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Error reading architecture data: {str(e)}"
        )

@app.get("/")
async def root():
    """Root endpoint providing API information"""
    return {
        "message": "Repo-Archi-Graph API - Powered by IBM Bob AI",
        "version": "1.0.0",
        "endpoints": {
            "/api/analyze": "Get IBM Bob AI-generated architectural analysis data"
        }
    }

if __name__ == "__main__":
    uvicorn.run(
        app,
        host="127.0.0.1",
        port=8080,
        log_level="info"
    )

# Made with Bob
